### ISSUE TITLE
question about similarity score

### ISSUE THREAD

**Issue by wjczf123** [xiami2019/CLAIF#1]
Hi, qinyuan. 

I have a question about similarity score in Section 3.3.

Why you train a model to generate a similarity score for Section 3.3?

It looks like I can straightforwardly use the LLM to generate similarity score directly.

Is there some special reason for this?

**Comment by xiami2019** [comment]
We train a model to encode sentences instead of generating similarity scores:)
Cause our goal is training an encoder to encode sentences and obtain sentence embeddings. 
STS benchmark is used to assess the quality of sentence embeddings.
LLMs can judge semantic similarities but can not obtain sentence embeddings directly.

**Comment by wjczf123** [comment]
Thanks. I got it.
And what is the relationship between Section 3.3 and 3.4? It looks like they are two ways to train a model.

**Comment by xiami2019** [comment]
Sec 3.3 is about training an encoder with AI feedback only (CLAIF) and Sec 3.4 is about how to combine human and AI feedback(CLHAIF). We use two loss functions for these two scenarios respectively. Please refer to Sec 2 for definitions of CLAIF and CLHAIF~

**Comment by wjczf123** [comment]
Thanks for your quick and detailed response. I understand. Thank you.
